package com.edugroupe.premierjpaform.jpa;

import java.util.*;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;
import javax.persistence.Persistence;

import com.edugroupe.premierjpaform.beans.Message;

public class JpaTest {

	
	/**
	 * @param args
	 */
	public static void main(String[] args) {
		EntityManagerFactory emf = Persistence.createEntityManagerFactory("testHibernate");
        Scanner input = new Scanner(System.in);

        input.nextLine();
        System.out.println("--------------------------------------");
		test1(emf);

        input.nextLine();
		System.out.println("--------------------------------------");
		test2(emf);

        input.nextLine();
		System.out.println("--------------------------------------");		

	    emf.close();
		System.out.println("done...");
	}




	public static void test1(EntityManagerFactory emf)
	{
		// on recupere un entityManager
		EntityManager em = emf.createEntityManager();
		// et une transaction
		EntityTransaction tx = em.getTransaction();
		tx.begin();
		//----------------------------------------------------
		Scanner input = new Scanner(System.in);
		System.out.println("titre message ? ");
		String titre = input.nextLine();
		System.out.println("corps message ? ");
		String corps = input.nextLine();
		// l'id est à 0, car c'est mysql qui determine l'id pour Message (autogenerated)
		Message msg = new Message(0, titre, corps);
		// la méthode persist permet de sauvegarde un objet dans la base
		// c'est forcément une insertion, on ne persiste pas un objet déjà présent
		// dans le base
		em.persist(msg);
		//----------------------------------------------------
		tx.commit();
		em.close();
	}


	public static void test2(EntityManagerFactory emf)
	{
		// on recupere un entityManager
		EntityManager em = emf.createEntityManager();
		// et une transaction
		EntityTransaction tx = em.getTransaction();
		tx.begin();
		//----------------------------------------------------
		
		Scanner input = new Scanner(System.in);
		System.out.println("identifiant message? ");
		int id = Integer.parseInt(input.nextLine());
		// find permet de retrouver/charger un objet depuis la base
		// avec sa clef primaire
		// 2 arguments -> type de l'objet/entite
		//				-> la valeur de la clef primaire
		Message msg = em.find(Message.class, id);
		// il me renvoie un objet message remplis a partir de la base s'il en trouve un
		
		if (msg != null) {
		    System.out.println(msg.getTitre());
		    System.out.println(msg.getCorps());
        }
        else {
		    System.out.println("message inconnu...");            
        }
		
		//----------------------------------------------------
		tx.commit();
		em.close();
	}

}
